//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
[System.Xml.Serialization.XmlRootAttribute("PublicationDelivery", Namespace="http://www.netex.org.uk/netex", IsNullable=false)]
public partial class PublicationDeliveryType {
    
    private string publicationTimestampField;
    
    private string participantRefField;
    
    private dataObjectsType dataObjectsField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PublicationTimestamp {
        get {
            return this.publicationTimestampField;
        }
        set {
            this.publicationTimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ParticipantRef {
        get {
            return this.participantRefField;
        }
        set {
            this.participantRefField = value;
        }
    }
    
    /// <remarks/>
    public dataObjectsType dataObjects {
        get {
            return this.dataObjectsField;
        }
        set {
            this.dataObjectsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class dataObjectsType {
    
    private CompositeFrameType compositeFrameField;
    
    /// <remarks/>
    public CompositeFrameType CompositeFrame {
        get {
            return this.compositeFrameField;
        }
        set {
            this.compositeFrameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class CompositeFrameType {
    
    private validityConditionsType validityConditionsField;
    
    private CodespaceType[] codespacesField;
    
    private FrameDefaultsType frameDefaultsField;
    
    private framesType framesField;
    
    private string idField;
    
    private string versionField;
    
    private string modificationField;
    
    /// <remarks/>
    public validityConditionsType validityConditions {
        get {
            return this.validityConditionsField;
        }
        set {
            this.validityConditionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Codespace", IsNullable=false)]
    public CodespaceType[] codespaces {
        get {
            return this.codespacesField;
        }
        set {
            this.codespacesField = value;
        }
    }
    
    /// <remarks/>
    public FrameDefaultsType FrameDefaults {
        get {
            return this.frameDefaultsField;
        }
        set {
            this.frameDefaultsField = value;
        }
    }
    
    /// <remarks/>
    public framesType frames {
        get {
            return this.framesField;
        }
        set {
            this.framesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string modification {
        get {
            return this.modificationField;
        }
        set {
            this.modificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class validityConditionsType {
    
    private ValidBetweenType validBetweenField;
    
    /// <remarks/>
    public ValidBetweenType ValidBetween {
        get {
            return this.validBetweenField;
        }
        set {
            this.validBetweenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class ValidBetweenType {
    
    private string fromDateField;
    
    private string toDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FromDate {
        get {
            return this.fromDateField;
        }
        set {
            this.fromDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ToDate {
        get {
            return this.toDateField;
        }
        set {
            this.toDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class VehicleJourneyRefType {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class BlockRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class CourseOfJourneysType {
    
    private string startTimeInBlockField;
    
    private BlockRefType blockRefField;
    
    private VehicleJourneyRefType[] journeysField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string StartTimeInBlock {
        get {
            return this.startTimeInBlockField;
        }
        set {
            this.startTimeInBlockField = value;
        }
    }
    
    /// <remarks/>
    public BlockRefType BlockRef {
        get {
            return this.blockRefField;
        }
        set {
            this.blockRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("VehicleJourneyRef", IsNullable=false)]
    public VehicleJourneyRefType[] journeys {
        get {
            return this.journeysField;
        }
        set {
            this.journeysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class coursesOfJourneysType {
    
    private CourseOfJourneysType courseOfJourneysField;
    
    /// <remarks/>
    public CourseOfJourneysType CourseOfJourneys {
        get {
            return this.courseOfJourneysField;
        }
        set {
            this.courseOfJourneysField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class endPointRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class startPointRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class VehicleTypeRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class BlockType {
    
    private string descriptionField;
    
    private VehicleTypeRefType vehicleTypeRefField;
    
    private startPointRefType startPointRefField;
    
    private endPointRefType endPointRefField;
    
    private coursesOfJourneysType coursesOfJourneysField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public VehicleTypeRefType VehicleTypeRef {
        get {
            return this.vehicleTypeRefField;
        }
        set {
            this.vehicleTypeRefField = value;
        }
    }
    
    /// <remarks/>
    public startPointRefType startPointRef {
        get {
            return this.startPointRefField;
        }
        set {
            this.startPointRefField = value;
        }
    }
    
    /// <remarks/>
    public endPointRefType endPointRef {
        get {
            return this.endPointRefField;
        }
        set {
            this.endPointRefField = value;
        }
    }
    
    /// <remarks/>
    public coursesOfJourneysType coursesOfJourneys {
        get {
            return this.coursesOfJourneysField;
        }
        set {
            this.coursesOfJourneysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class VehicleScheduleFrameType {
    
    private BlockType[] blocksField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Block", IsNullable=false)]
    public BlockType[] blocks {
        get {
            return this.blocksField;
        }
        set {
            this.blocksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class StopPointInJourneyPatternRefType {
    
    private string versionField;
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class TimetabledPassingTimeType {
    
    private StopPointInJourneyPatternRefType stopPointInJourneyPatternRefField;
    
    private string arrivalTimeField;
    
    private string arrivalDayOffsetField;
    
    private string[] departureTimeField;
    
    private string[] departureDayOffsetField;
    
    /// <remarks/>
    public StopPointInJourneyPatternRefType StopPointInJourneyPatternRef {
        get {
            return this.stopPointInJourneyPatternRefField;
        }
        set {
            this.stopPointInJourneyPatternRefField = value;
        }
    }
    
    /// <remarks/>
    public string ArrivalTime {
        get {
            return this.arrivalTimeField;
        }
        set {
            this.arrivalTimeField = value;
        }
    }
    
    /// <remarks/>
    public string ArrivalDayOffset {
        get {
            return this.arrivalDayOffsetField;
        }
        set {
            this.arrivalDayOffsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DepartureTime")]
    public string[] DepartureTime {
        get {
            return this.departureTimeField;
        }
        set {
            this.departureTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DepartureDayOffset")]
    public string[] DepartureDayOffset {
        get {
            return this.departureDayOffsetField;
        }
        set {
            this.departureDayOffsetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class JourneyPatternRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class DayTypeRefType {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class ServiceJourneyType {
    
    private DayTypeRefType[] dayTypesField;
    
    private JourneyPatternRefType journeyPatternRefField;
    
    private TimetabledPassingTimeType[] passingTimesField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("DayTypeRef", IsNullable=false)]
    public DayTypeRefType[] dayTypes {
        get {
            return this.dayTypesField;
        }
        set {
            this.dayTypesField = value;
        }
    }
    
    /// <remarks/>
    public JourneyPatternRefType JourneyPatternRef {
        get {
            return this.journeyPatternRefField;
        }
        set {
            this.journeyPatternRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("TimetabledPassingTime", IsNullable=false)]
    public TimetabledPassingTimeType[] passingTimes {
        get {
            return this.passingTimesField;
        }
        set {
            this.passingTimesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class TimetableFrameType {
    
    private ServiceJourneyType[] vehicleJourneysField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ServiceJourney", IsNullable=false)]
    public ServiceJourneyType[] vehicleJourneys {
        get {
            return this.vehicleJourneysField;
        }
        set {
            this.vehicleJourneysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class DestinationDisplayRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class StopPointInJourneyPatternType {
    
    private ScheduledStopPointRefType scheduledStopPointRefField;
    
    private string forAlightingField;
    
    private string forBoardingField;
    
    private DestinationDisplayRefType[] destinationDisplayRefField;
    
    private string idField;
    
    private string versionField;
    
    private int orderField;
    
    private bool orderFieldSpecified;
    
    /// <remarks/>
    public ScheduledStopPointRefType ScheduledStopPointRef {
        get {
            return this.scheduledStopPointRefField;
        }
        set {
            this.scheduledStopPointRefField = value;
        }
    }
    
    /// <remarks/>
    public string ForAlighting {
        get {
            return this.forAlightingField;
        }
        set {
            this.forAlightingField = value;
        }
    }
    
    /// <remarks/>
    public string ForBoarding {
        get {
            return this.forBoardingField;
        }
        set {
            this.forBoardingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DestinationDisplayRef")]
    public DestinationDisplayRefType[] DestinationDisplayRef {
        get {
            return this.destinationDisplayRefField;
        }
        set {
            this.destinationDisplayRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool orderSpecified {
        get {
            return this.orderFieldSpecified;
        }
        set {
            this.orderFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class ScheduledStopPointRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class RouteRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class JourneyPatternType {
    
    private RouteRefType routeRefField;
    
    private StopPointInJourneyPatternType[] pointsInSequenceField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    public RouteRefType RouteRef {
        get {
            return this.routeRefField;
        }
        set {
            this.routeRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("StopPointInJourneyPattern", IsNullable=false)]
    public StopPointInJourneyPatternType[] pointsInSequence {
        get {
            return this.pointsInSequenceField;
        }
        set {
            this.pointsInSequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class QuayRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class StopPlaceRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class PassengerStopAssignmentType {
    
    private ScheduledStopPointRefType scheduledStopPointRefField;
    
    private StopPlaceRefType stopPlaceRefField;
    
    private QuayRefType quayRefField;
    
    private string idField;
    
    private string versionField;
    
    private int orderField;
    
    private bool orderFieldSpecified;
    
    /// <remarks/>
    public ScheduledStopPointRefType ScheduledStopPointRef {
        get {
            return this.scheduledStopPointRefField;
        }
        set {
            this.scheduledStopPointRefField = value;
        }
    }
    
    /// <remarks/>
    public StopPlaceRefType StopPlaceRef {
        get {
            return this.stopPlaceRefField;
        }
        set {
            this.stopPlaceRefField = value;
        }
    }
    
    /// <remarks/>
    public QuayRefType QuayRef {
        get {
            return this.quayRefField;
        }
        set {
            this.quayRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool orderSpecified {
        get {
            return this.orderFieldSpecified;
        }
        set {
            this.orderFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class ScheduledStopPointType {
    
    private string nameField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class DestinationDisplayType {
    
    private string frontTextField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FrontText {
        get {
            return this.frontTextField;
        }
        set {
            this.frontTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class RepresentedByGroupRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class OperatorRefType {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class LineType {
    
    private string nameField;
    
    private string transportModeField;
    
    private string publicCodeField;
    
    private OperatorRefType operatorRefField;
    
    private string monitoredField;
    
    private RepresentedByGroupRefType representedByGroupRefField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TransportMode {
        get {
            return this.transportModeField;
        }
        set {
            this.transportModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PublicCode {
        get {
            return this.publicCodeField;
        }
        set {
            this.publicCodeField = value;
        }
    }
    
    /// <remarks/>
    public OperatorRefType OperatorRef {
        get {
            return this.operatorRefField;
        }
        set {
            this.operatorRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Monitored {
        get {
            return this.monitoredField;
        }
        set {
            this.monitoredField = value;
        }
    }
    
    /// <remarks/>
    public RepresentedByGroupRefType RepresentedByGroupRef {
        get {
            return this.representedByGroupRefField;
        }
        set {
            this.representedByGroupRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class RoutePointRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class PointOnRouteType {
    
    private RoutePointRefType routePointRefField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    public RoutePointRefType RoutePointRef {
        get {
            return this.routePointRefField;
        }
        set {
            this.routePointRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class DirectionRefType {
    
    private string versionField;
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class LineRef1Type {
    
    private string versionField;
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class RouteType {
    
    private string nameField;
    
    private LineRef1Type lineRefField;
    
    private DirectionRefType directionRefField;
    
    private PointOnRouteType[] pointsInSequenceField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public LineRef1Type LineRef {
        get {
            return this.lineRefField;
        }
        set {
            this.lineRefField = value;
        }
    }
    
    /// <remarks/>
    public DirectionRefType DirectionRef {
        get {
            return this.directionRefField;
        }
        set {
            this.directionRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PointOnRoute", IsNullable=false)]
    public PointOnRouteType[] pointsInSequence {
        get {
            return this.pointsInSequenceField;
        }
        set {
            this.pointsInSequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class ProjectedPointRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class PointProjectionType {
    
    private ProjectedPointRefType projectedPointRefField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    public ProjectedPointRefType ProjectedPointRef {
        get {
            return this.projectedPointRefField;
        }
        set {
            this.projectedPointRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class projectionsType {
    
    private PointProjectionType pointProjectionField;
    
    /// <remarks/>
    public PointProjectionType PointProjection {
        get {
            return this.pointProjectionField;
        }
        set {
            this.pointProjectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class RoutePointType {
    
    private projectionsType projectionsField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    public projectionsType projections {
        get {
            return this.projectionsField;
        }
        set {
            this.projectionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class DirectionType {
    
    private string nameField;
    
    private string descriptionField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class LineRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class GroupOfLinesType {
    
    private string nameField;
    
    private LineRefType[] membersField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LineRef", IsNullable=false)]
    public LineRefType[] members {
        get {
            return this.membersField;
        }
        set {
            this.membersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class groupsOfLinesType {
    
    private GroupOfLinesType groupOfLinesField;
    
    /// <remarks/>
    public GroupOfLinesType GroupOfLines {
        get {
            return this.groupOfLinesField;
        }
        set {
            this.groupOfLinesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class AuthorityRefType {
    
    private string refField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class NetworkType {
    
    private string nameField;
    
    private AuthorityRefType authorityRefField;
    
    private groupsOfLinesType groupsOfLinesField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public AuthorityRefType AuthorityRef {
        get {
            return this.authorityRefField;
        }
        set {
            this.authorityRefField = value;
        }
    }
    
    /// <remarks/>
    public groupsOfLinesType groupsOfLines {
        get {
            return this.groupsOfLinesField;
        }
        set {
            this.groupsOfLinesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class ServiceFrameType {
    
    private NetworkType networkField;
    
    private DirectionType[] directionsField;
    
    private RoutePointType[] routePointsField;
    
    private RouteType[] routesField;
    
    private LineType[] linesField;
    
    private DestinationDisplayType[] destinationDisplaysField;
    
    private ScheduledStopPointType[] scheduledStopPointsField;
    
    private PassengerStopAssignmentType[] stopAssignmentsField;
    
    private JourneyPatternType[] journeyPatternsField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    public NetworkType Network {
        get {
            return this.networkField;
        }
        set {
            this.networkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Direction", IsNullable=false)]
    public DirectionType[] directions {
        get {
            return this.directionsField;
        }
        set {
            this.directionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("RoutePoint", IsNullable=false)]
    public RoutePointType[] routePoints {
        get {
            return this.routePointsField;
        }
        set {
            this.routePointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Route", IsNullable=false)]
    public RouteType[] routes {
        get {
            return this.routesField;
        }
        set {
            this.routesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Line", IsNullable=false)]
    public LineType[] lines {
        get {
            return this.linesField;
        }
        set {
            this.linesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("DestinationDisplay", IsNullable=false)]
    public DestinationDisplayType[] destinationDisplays {
        get {
            return this.destinationDisplaysField;
        }
        set {
            this.destinationDisplaysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ScheduledStopPoint", IsNullable=false)]
    public ScheduledStopPointType[] scheduledStopPoints {
        get {
            return this.scheduledStopPointsField;
        }
        set {
            this.scheduledStopPointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PassengerStopAssignment", IsNullable=false)]
    public PassengerStopAssignmentType[] stopAssignments {
        get {
            return this.stopAssignmentsField;
        }
        set {
            this.stopAssignmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("JourneyPattern", IsNullable=false)]
    public JourneyPatternType[] journeyPatterns {
        get {
            return this.journeyPatternsField;
        }
        set {
            this.journeyPatternsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class LocationType {
    
    private System.Nullable<decimal> longitudeField;
    
    private System.Nullable<decimal> latitudeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class CentroidType {
    
    private LocationType locationField;
    
    /// <remarks/>
    public LocationType Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class QuayType {
    
    private CentroidType centroidField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    public CentroidType Centroid {
        get {
            return this.centroidField;
        }
        set {
            this.centroidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class StopPlaceType {
    
    private string nameField;
    
    private string stopPlaceType1Field;
    
    private QuayType[] quaysField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StopPlaceType", IsNullable=true)]
    public string StopPlaceType1 {
        get {
            return this.stopPlaceType1Field;
        }
        set {
            this.stopPlaceType1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Quay", IsNullable=false)]
    public QuayType[] quays {
        get {
            return this.quaysField;
        }
        set {
            this.quaysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class SiteFrameType {
    
    private StopPlaceType[] stopPlacesField;
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("StopPlace", IsNullable=false)]
    public StopPlaceType[] stopPlaces {
        get {
            return this.stopPlacesField;
        }
        set {
            this.stopPlacesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class framesType {
    
    private SiteFrameType siteFrameField;
    
    private ServiceFrameType serviceFrameField;
    
    private TimetableFrameType timetableFrameField;
    
    private VehicleScheduleFrameType vehicleScheduleFrameField;
    
    /// <remarks/>
    public SiteFrameType SiteFrame {
        get {
            return this.siteFrameField;
        }
        set {
            this.siteFrameField = value;
        }
    }
    
    /// <remarks/>
    public ServiceFrameType ServiceFrame {
        get {
            return this.serviceFrameField;
        }
        set {
            this.serviceFrameField = value;
        }
    }
    
    /// <remarks/>
    public TimetableFrameType TimetableFrame {
        get {
            return this.timetableFrameField;
        }
        set {
            this.timetableFrameField = value;
        }
    }
    
    /// <remarks/>
    public VehicleScheduleFrameType VehicleScheduleFrame {
        get {
            return this.vehicleScheduleFrameField;
        }
        set {
            this.vehicleScheduleFrameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class DefaultLocaleType {
    
    private string timeZoneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TimeZone {
        get {
            return this.timeZoneField;
        }
        set {
            this.timeZoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class DefaultDataSourceRefType {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class FrameDefaultsType {
    
    private DefaultDataSourceRefType defaultDataSourceRefField;
    
    private DefaultLocaleType defaultLocaleField;
    
    /// <remarks/>
    public DefaultDataSourceRefType DefaultDataSourceRef {
        get {
            return this.defaultDataSourceRefField;
        }
        set {
            this.defaultDataSourceRefField = value;
        }
    }
    
    /// <remarks/>
    public DefaultLocaleType DefaultLocale {
        get {
            return this.defaultLocaleField;
        }
        set {
            this.defaultLocaleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.netex.org.uk/netex")]
public partial class CodespaceType {
    
    private string xmlnsField;
    
    private string xmlnsUrlField;
    
    private string descriptionField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Xmlns {
        get {
            return this.xmlnsField;
        }
        set {
            this.xmlnsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string XmlnsUrl {
        get {
            return this.xmlnsUrlField;
        }
        set {
            this.xmlnsUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
